---
name: Linter Job

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check for linting errors
        if: failure()
        run: |
          echo "Linting issues were detected. Please see the summary report."
          cat super-linter-output/super-linter-summary.md || echo "No summary available."
