---
name: Linter Job

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Linter
        uses: github/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main

      - name: Check for linting errors
        if: failure()
        run: |
          echo "Linting issues were detected. Please see the summary report."
          cat super-linter-output/super-linter-summary.md
