name: Super Linter

on:
  push:
  pull_request:

permissions: {}

jobs:
  lint:
    name: Run Super-Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Run Super-Linter
        uses: github/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main  # Specify your default branch if not 'main' 

      - name: Check for linting errors
        if: failure()
        run: |
          echo "Linting issues were detected. Please see summary report."
          cat super-linter-output/super-linter-summary.md  # Display the summary

